services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-redis
    restart: on-failure
    ports:
      - "6379:6379"
      - '8001:8001'
    networks:
      - backend
  voter-api:
    image: voter-api:latest
    container_name: voter-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1080:1080"
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true